# .github/FUNDING.yml
# Поддержка проекта через GitHub Sponsors и криптовалюту

github: [misht-world]
custom: 
  - 'bitcoin:bc1qy5la5xsswx2hnukf76x5g2spjpvf6n7ak56rnu'
  - 'ethereum:0x75F27F55Fa87d13C267c304E7e3a0afeB0f660a9'
  - 'https://www.paypal.com/paypalme/MikhailZhi'